name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config user.name "bit-buddy"
          git config user.email "detetoaz@gmail.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/SirLex/UP.git

      - name: Fetch and merge upstream
        run: |
          git fetch upstream
          git checkout main # Change to your default branch if needed
          git merge upstream/main

      - name: Push changes to forked repo
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
